algo=ETHASH
pool=ethash.unmineable.com:3333
user=XMR:85PGPCP6gpSYRphqmk8HS8cK7aPghX1puBvf3GA1WxvxFpCYK7mrt2q4UDQkRprgci67jgeTDfmAhMxZVjYMaAtaPhQkxKS.DN

################################################################################
# Comfort functions
################################################################################

# apiport=<the port to open api>
# shortstats=<interval between the short statiscics>
# longstats=<interval between the verbose statiscics>


################################################################################
# Comfort functions
################################################################################

# apiport=<the port to open api>
# shortstats=<interval between the short statiscics>
# longstats=<interval between the verbose statiscics>

